"""KiCad type definitions.

Contains immutable dataclasses for representing KiCad file structures.
"""

from .symbol import (
    PinDef,
    Rectangle,
    Circle,
    Arc,
    Polyline,
    Text,
    GraphicElement,
    SymbolUnit,
    SymbolDef,
    SymbolLibrary,
)

from .schematic import (
    Wire,
    Bus,
    BusEntry,
    Junction,
    NoConnect,
    Label,
    GlobalLabel,
    HierarchicalLabel,
    PowerLabel,
    SymbolPin,
    SymbolInstance,
    SheetPin,
    Sheet,
    Text as SchematicText,
    SchematicPage,
    TitleBlock,
    LibSymbol,
    Schematic,
)

from .primitives import (
    Point,
    Position,
    UUID,
    Color,
    Stroke,
    Fill,
    Font,
    Effects,
    Property,
    COLOR_BLACK,
    COLOR_WHITE,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_BLUE,
    COLOR_YELLOW,
    COLOR_TRANSPARENT,
    STROKE_DEFAULT,
    FILL_NONE,
    FILL_OUTLINE,
    FILL_BACKGROUND,
    FONT_DEFAULT,
    EFFECTS_DEFAULT,
    EFFECTS_HIDDEN,
)

from .enums import (
    PinElectricalType,
    PinShape,
    PinOrientation,
    FillType,
    StrokeType,
    LabelShape,
    JustifyHorizontal,
    JustifyVertical,
    Severity,
    PowerFlag,
    SheetPinType,
    SymbolUnit,
    PIN_COMPATIBILITY,
    check_pin_compatibility,
)

__all__ = [
    # Symbol types
    "PinDef",
    "Rectangle",
    "Circle",
    "Arc",
    "Polyline",
    "Text",
    "GraphicElement",
    "SymbolUnit",
    "SymbolDef",
    "SymbolLibrary",
    # Schematic types
    "Wire",
    "Bus",
    "BusEntry",
    "Junction",
    "NoConnect",
    "Label",
    "GlobalLabel",
    "HierarchicalLabel",
    "PowerLabel",
    "SymbolPin",
    "SymbolInstance",
    "SheetPin",
    "Sheet",
    "SchematicText",
    "SchematicPage",
    "TitleBlock",
    "LibSymbol",
    "Schematic",
    # Primitives
    "Point",
    "Position",
    "UUID",
    "Color",
    "Stroke",
    "Fill",
    "Font",
    "Effects",
    "Property",
    # Primitive constants
    "COLOR_BLACK",
    "COLOR_WHITE",
    "COLOR_RED",
    "COLOR_GREEN",
    "COLOR_BLUE",
    "COLOR_YELLOW",
    "COLOR_TRANSPARENT",
    "STROKE_DEFAULT",
    "FILL_NONE",
    "FILL_OUTLINE",
    "FILL_BACKGROUND",
    "FONT_DEFAULT",
    "EFFECTS_DEFAULT",
    "EFFECTS_HIDDEN",
    # Enums
    "PinElectricalType",
    "PinShape",
    "PinOrientation",
    "FillType",
    "StrokeType",
    "LabelShape",
    "JustifyHorizontal",
    "JustifyVertical",
    "Severity",
    "PowerFlag",
    "SheetPinType",
    "SymbolUnit",
    # Functions
    "PIN_COMPATIBILITY",
    "check_pin_compatibility",
]
